In [1]:
import pandas as pd
import numpy as np
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

from sklearn import datasets
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df= pd.read_csv('Chinese database.csv') 
df

Attribute 1  Attribute 2  Attribute 3  Attribute 4  Attribute 5  \
0        0.328470     0.621909     0.681941     0.077886     0.000000   
1        0.000000     0.000000     0.681941     0.000000     0.000000   
2        0.325102     0.517464     0.000000     0.059524     0.000000   
3        0.346195     0.478459     0.095400     0.038364     0.000000   
4        0.656937     0.627607     0.000000     0.077364     0.000000   
...           ...          ...          ...          ...          ...   
3106     0.505164     0.501044     0.144278     0.115629     0.269147   
3107     0.419075     0.479698     0.129756     0.099920     0.259097   
3108     0.419075     0.479698     0.129756     0.099920     0.259097   
3109     0.419075     0.479698     0.129756     0.099920     0.259097   
3110     0.419075     0.479698     0.129756     0.099920     0.259097   

      Attribute 6  Attribute 7  Attribute 8  Attribute 9  Attribute 10  ...  \
0        0.466059          1.0     1.000000     0.031412      0.894724  ...   
1        0.000000          0.0     0.000000     0.000000      0.000000  ...   
2        0.467174          1.0     0.641464     0.070322      0.587853  ...   
3        0.459010          1.0     0.476235     0.000138      0.515098  ...   
4        0.496723          1.0     0.805214     0.067969      0.546627  ...   
...           ...          ...          ...          ...           ...  ...   
3106     0.462915          1.0     0.547183     0.103255      0.185312  ...   
3107     0.463688          1.0     0.480785     0.118558      0.555160  ...   
3108     0.463688          1.0     0.480785     0.118558      0.555160  ...   
3109     0.463688          1.0     0.480785     0.118558      0.555160  ...   
3110     0.463688          1.0     0.480785     0.118558      0.555160  ...   

      Attribute 71  Attribute 72  Attribute 73  Attribute 74  Attribute 75  \
0              0.2           0.0           0.0      0.626321      0.239027   
1              0.2           0.0           0.0      0.694637      0.239027   
2              1.0           0.5           1.0      0.721803      0.239027   
3              0.2           0.0           0.0      0.866284      0.239027   
4              1.0           0.5           1.0      0.694637      0.239027   
...            ...           ...           ...           ...           ...   
3106           1.0           0.5           1.0      0.742429      0.737164   
3107           1.0           0.5           1.0      0.742429      0.737164   
3108           1.0           0.5           1.0      0.742429      0.737164   
3109           1.0           0.5           1.0      0.742429      0.737164   
3110           1.0           0.5           1.0      0.742429      0.737164   

      Attribute 76  Attribute 77  Attribute 78  Attribute 79  Y  
0         0.356067       0.97561      0.182182      0.650655  1  
1         0.356067       0.97561      0.182182      0.650655  0  
2         0.356067       0.97561      0.182182      0.650655  0  
3         0.356067       0.97561      0.182182      0.650655  1  
4         0.356067       0.97561      0.182182      0.650655  0  
...            ...           ...           ...           ... ..  
3106      0.269593       0.97561      0.639636      0.755459  0  
3107      0.269593       0.97561      0.639636      0.755459  0  
3108      0.269593       0.97561      0.639636      0.755459  0  
3109      0.269593       0.97561      0.639636      0.755459  0  
3110      0.269593       0.97561      0.639636      0.755459  0  

[3111 rows x 80 columns]

In [3]:
df.shape

(3111, 80)

In [4]:
X = df.iloc[:, 0:79]
y = df.iloc[:, 79]

# LDA

In [5]:
lda = LDA(n_components=1)
lda_X = lda.fit(X,y).transform(X)

In [6]:

#plt.scatter(lda_X[y == 0, 0],lda_X[y == 0, 0], s =80, c = 'orange', label = 'Type 0')
#plt.scatter(lda_X[y == 1, 0],lda_X[y == 1, 0], s =80,  c = 'yellow', label = 'Type 1')
#plt.scatter(lda_X[y == 2, 0], lda_X[y == 2, 1], s =80,  c = 'green', label = 'Type 2')
#plt.title('LDA plot for Wine Dataset')
#plt.legend()

In [7]:
# Importing Libraries for Modelling.
from sklearn import neighbors, datasets, preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [21]:
X=lda_X
y=y

In [22]:
#Setting training and testing values

Xtrain, Xtest, y_train, y_test = train_test_split(X, y)
scaler = preprocessing.StandardScaler().fit(Xtrain)
Xtrain = scaler.transform(Xtrain)
Xtest = scaler.transform(Xtest)

# Using KMN

In [23]:
# Modeling is done using KNN classifiers.
knn = neighbors.KNeighborsClassifier(n_neighbors=2)
knn.fit(Xtrain, y_train)
y_pred = knn.predict(Xtest)


# Display the Output

print('Accuracy Score:', accuracy_score(y_test, y_pred))
print('Confusion matrix \n',  confusion_matrix(y_test, y_pred))
print('Classification \n', classification_report(y_test, y_pred))

Accuracy Score: 0.9794344473007712
Confusion matrix 
 [[756   3]
 [ 13   6]]
Classification 
               precision    recall  f1-score   support

           0       0.98      1.00      0.99       759
           1       0.67      0.32      0.43        19

    accuracy                           0.98       778
   macro avg       0.82      0.66      0.71       778
weighted avg       0.98      0.98      0.98       778



# Logistic Regression Accuracy

In [24]:
#Logistic Regression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(Xtrain,y_train)
y_pred = classifier.predict(Xtest)
cm = confusion_matrix(y_test,y_pred)
accuracy = accuracy_score(y_test,y_pred)
print("Logistic Regression :")
print("Accuracy = ", accuracy)
print(cm)

Logistic Regression :
Accuracy =  0.9755784061696658
[[753   6]
 [ 13   6]]


# LR Cohen Kappa Accuracy

In [25]:
from sklearn.metrics import cohen_kappa_score
cluster = cohen_kappa_score(y_test, y_pred)
cluster

0.37528526751753866

# Support Vector Machine Accuracy

In [26]:
Xtrain, Xtest, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [27]:
#Support Vector Machine
from sklearn.svm import SVC
classifier = SVC()
classifier.fit(Xtrain,y_train)
y_pred = classifier.predict(Xtest)
cm = confusion_matrix(y_test,y_pred)
accuracy = accuracy_score(y_test,y_pred)
print("Support Vector Machine:")
print("Accuracy = ", accuracy)
print(cm)

Support Vector Machine:
Accuracy =  0.9823434991974318
[[608   1]
 [ 10   4]]


# Gaussian Naive Bayes Accuracy

In [28]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(Xtrain,y_train)
y_pred = classifier.predict(Xtest)
cm = confusion_matrix(y_test,y_pred)
accuracy = accuracy_score(y_test,y_pred)
print("Gaussian Naive Bayes :")
print("Accuracy = ", accuracy)
print(cm)

Gaussian Naive Bayes :
Accuracy =  0.9727126805778491
[[599  10]
 [  7   7]]


# Decision Tree Classifier Accuracy

In [29]:
Xtrain, Xtest, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [30]:
from sklearn.model_selection import train_test_split


from sklearn.tree import DecisionTreeClassifier as DT
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

classifier = DT(criterion='entropy', random_state=0)
classifier.fit(Xtrain,y_train)
y_pred = classifier.predict(Xtest)
cm = confusion_matrix(y_test,y_pred)
print("Decision Tree Classifier :")
print("Accuracy = ", accuracy)
print(cm)

Decision Tree Classifier :
Accuracy =  0.9727126805778491
[[604   5]
 [  8   6]]


# Random Forest Classifier Accuracy

In [31]:
#Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier as RF
classifier = RF(n_estimators=10, criterion='entropy', random_state=0)
classifier.fit(Xtrain,y_train)
y_pred = classifier.predict(Xtest)
cm = confusion_matrix(y_test,y_pred)
print("Random Forest Classifier :")
print("Accuracy = ", accuracy)
print(cm)

Random Forest Classifier :
Accuracy =  0.9727126805778491
[[605   4]
 [  8   6]]
